### ISSUE TITLE
dll加载失败

### ISSUE THREAD

**Issue by kagg886** [SwaggyMacro/MiraiNsfwBot#5]
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\Administrator\AppData\Local\Temp\onnxruntime-java5497093949429325597\onnxruntime.dll: Can't find dependent libraries
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2383)
	at java.base/java.lang.Runtime.load0(Runtime.java:746)
	at java.base/java.lang.System.load(System.java:1857)
	at ai.onnxruntime.OnnxRuntime.load(OnnxRuntime.java:318)
	at ai.onnxruntime.OnnxRuntime.init(OnnxRuntime.java:135)
	at ai.onnxruntime.OrtEnvironment.<clinit>(OrtEnvironment.java:25)
	at ai.AntiModel.detector(AntiModel.java:59)
	at Main.main(Main.java:11)

**Comment by SwaggyMacro** [comment]
我在本机和服务器都没有发生过这个问题，可能是onnxruntime不能正确加载。
可以谷歌一下相关问题：
java.lang.UnsatisfiedLinkError: dll: Can't find dependent libraries
onnxruntime.dll: Can't find dependent libraries

**Comment by SwaggyMacro** [comment]
我这里存在API-MS-WIN开头的DLL依赖。
可能是JDK问题？
看到了一个相关问题 https://blog.csdn.net/eifjgoergfgrgr/article/details/119613094
![image](https://user-images.githubusercontent.com/38845682/172091288-c0f515b8-2496-425d-9885-34027b41edd0.png)

**Comment by SwaggyMacro** [comment]
> 我的开发环境是Java16。 但是我百度了许久也找不到如图的那几个dll。 所以能否按需提取出来并给我一个链接？

可以尝试下调jdk版本
